name: cabal

on:
  push:
    branches: [ci-cabal, wip/build-matrix]
  pull_request:
    branches: [master]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.0"]
        ghc:
          - "8.4.4"
          - "8.6.5"
          - "8.8.3"
          - "8.10.1"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-haskell@v1
      name: setup GHC and cabal-install
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v1
      name: cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: build
      run: |
        cabal v2-update
        cabal v2-build all --enable-tests

    - name: simple
      run: cabal v2-test simple --test-show-details=direct --test-option="--color=always"

    - name: gdiff
      run: cabal v2-test gdiff --test-show-details=direct --test-option="--color=always"

    - name: plant
      run: cabal v2-test plant --test-show-details=direct --test-option="--color=always"

    - name: market
      run: cabal v2-test market --test-show-details=direct --test-option="--color=always"
